name: "HEMS"
description: "Home Energy Management System (HEMS)"
version: "1.0.0"
slug: "hems_api"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
ports:
  8000/tcp: 8000
startup: services
host_network: true
homeassistant_api: true
